-- 0002_strategies.sql —— 策略模板 + 分析结果（全新表）

CREATE TABLE IF NOT EXISTS strategy_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  description TEXT,
  system_prompt TEXT NOT NULL,
  user_prompt_template TEXT NOT NULL,
  output_schema JSONB NOT NULL DEFAULT '{}',
  model_provider TEXT,
  model_name TEXT,
  max_tokens INT DEFAULT 2048,
  is_builtin BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS strategy_templates_slug_idx ON strategy_templates(slug);
CREATE INDEX IF NOT EXISTS strategy_templates_active_idx ON strategy_templates(is_active);

CREATE TABLE IF NOT EXISTS analysis_results (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id BIGINT NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  strategy_id UUID NOT NULL REFERENCES strategy_templates(id) ON DELETE CASCADE,
  result JSONB NOT NULL DEFAULT '{}',
  category TEXT,
  tags TEXT[],
  score INT,
  priority INT,
  sentiment TEXT,
  model_provider TEXT,
  model_name TEXT,
  tokens_used INT,
  duration_ms INT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
CREATE INDEX IF NOT EXISTS analysis_results_article_idx ON analysis_results(article_id);
CREATE INDEX IF NOT EXISTS analysis_results_strategy_idx ON analysis_results(strategy_id);
CREATE INDEX IF NOT EXISTS analysis_results_category_idx ON analysis_results(category);
CREATE INDEX IF NOT EXISTS analysis_results_score_idx ON analysis_results(score DESC NULLS LAST);
CREATE INDEX IF NOT EXISTS analysis_results_tags_gin ON analysis_results USING GIN(tags);
CREATE INDEX IF NOT EXISTS analysis_results_result_gin ON analysis_results USING GIN(result);
CREATE INDEX IF NOT EXISTS analysis_results_created_idx ON analysis_results(created_at DESC);
