import { randomUUID } from 'node:crypto';
import os from 'node:os';
import path from 'node:path';
import { writeFile, unlink } from 'node:fs/promises';
import { getPool } from '@/server/infra/db/pool';
import { getPlainRssHubCookie } from '@/server/domains/rsshubCookie/services/rssHubCookieService';

/**
 * 抖音下载 / 文案提取的 Cookie 注入工具。
 *
 * 抖音反爬要求 yt-dlp 携带登录态 Cookie 才能解析 / 下载视频，否则报
 * "Fresh cookies (not necessarily logged in) are needed"。
 *
 * 安全约定（与 rssHubCookieService 一致）：
 * - 明文 Cookie 只写进临时 cookies.txt（Netscape 格式）供 yt-dlp --cookies 读取；
 * - 明文绝不进入任何日志 / DTO；
 * - 临时文件用后即删。
 */

/** 抖音相关域名（含短链 v.douyin.com 与分享页 iesdouyin.com）。 */
const DOUYIN_HOSTS = ['douyin.com', 'iesdouyin.com'];

export function isDouyinUrl(url: string): boolean {
  try {
    const host = new URL(url).hostname;
    return DOUYIN_HOSTS.some((h) => host === h || host.endsWith(`.${h}`));
  } catch {
    return false;
  }
}

export interface DouyinCookieArgs {
  /** 需附加到 yt-dlp 命令的参数（如 ['--cookies', '/tmp/...']）。无 Cookie 时为 []。 */
  args: string[];
  /** 必须在 yt-dlp 调用结束后调用，删除临时 Cookie 文件。 */
  cleanup: () => Promise<void>;
}

const NOOP_CLEANUP: () => Promise<void> = async () => {};

/**
 * 为一次 yt-dlp 调用构建抖音 Cookie 参数。
 *
 * 仅在「URL 是抖音」且「提供了 userId」时读取数据库；否则返回空参数，
 * 避免无关请求产生数据库查询与临时文件。
 *
 * 用法：
 * ```ts
 * const { args, cleanup } = await buildDouyinCookieArgs(url, userId);
 * try {
 *   await execFileAsync(bin, [...baseArgs, ...args, url]);
 * } finally {
 *   await cleanup();
 * }
 * ```
 */
export async function buildDouyinCookieArgs(
  url: string,
  userId?: number,
): Promise<DouyinCookieArgs> {
  if (!userId || !isDouyinUrl(url)) {
    return { args: [], cleanup: NOOP_CLEANUP };
  }

  const cookie = await getPlainRssHubCookie(getPool(), String(userId), 'douyin');
  if (!cookie) {
    return { args: [], cleanup: NOOP_CLEANUP };
  }

  const file = path.join(os.tmpdir(), `feedfuse_douyin_cookies_${randomUUID()}.txt`);
  const lines = ['# Netscape HTTP Cookie File', '# generated by FeedFuse for yt-dlp douyin download'];
  for (const pair of cookie.split(/;\s*/)) {
    const idx = pair.indexOf('=');
    if (idx <= 0) continue;
    lines.push(
      `#HttpOnly_.douyin.com\tTRUE\t/\tTRUE\t0\t${pair.slice(0, idx)}\t${pair.slice(idx + 1)}`,
    );
  }
  await writeFile(file, lines.join('\n'), { mode: 0o600 });

  return {
    args: ['--cookies', file],
    cleanup: async () => {
      await unlink(file).catch(() => {});
    },
  };
}
