-- 推荐订阅源表：系统内置推荐源
create table if not exists recommended_feeds (
  id bigint generated by default as identity primary key,
  title text not null,
  url text not null,
  site_url text null,
  icon_url text null,
  description text null,
  position int not null default 0,
  created_at timestamptz not null default now()
);
create unique index if not exists recommended_feeds_url_unique on recommended_feeds (url);