-- 启用 pgvector 扩展
create extension if not exists vector;

-- 知识库向量表
create table if not exists knowledge_embeddings (
  id bigint generated by default as identity primary key,
  article_id bigint not null references articles(id) on delete cascade,
  chunk_index int not null,
  chunk_text text not null,
  embedding vector(1536),
  created_at timestamptz not null default now()
);

create index if not exists knowledge_embeddings_article_id_idx on knowledge_embeddings (article_id);
create index if not exists knowledge_embeddings_embedding_idx on knowledge_embeddings using ivfflat (embedding vector_cosine_ops) with (lists = 100);

-- 全文搜索索引
create index if not exists knowledge_embeddings_chunk_text_gin on knowledge_embeddings using gin (to_tsvector('simple', chunk_text));